### ISSUE TITLE
Screenreader vs UI Test Automation

### ISSUE THREAD

**Issue by grvermeulen** [Notalib/nativescript-accessibility-ext#11]
Hi,
Its maybe not really an issue, but more a question:
We have the following case:

We want our app to be accessible for screenreaders with specific texts that make sense for the user,
At the same time use the automationText as an identifier for automated UI testing.
The app is multi-langual so it would be awsome to use the automationText as a unique identifier for all languages (and platforms), but then the screenreader reads the automationText which doesn't make sense for the user.

Is it possible to solve this for example with different attributes (besides automationText) or in another way? Would the function view.accessibiltyAnnouncement be an option?

Thanks in advance!

Guido

**Comment by m-abs** [comment]
Hi,

You're not the only that have a problem with {N} mapping `automationText` to both `accessibilityLabel` AND `accessibilityIdentifier`.

I forgot to update the README, but in the plugin for {N} 3.0+ we've added the property 
 `accessibilityLabel` which sets `contentDescription` on Android and `accessibilityLabel` on `iOS`.
This conflicts with `automationText`, so don't use both.

`accessibilityIdentifier` is the property you want for testing, but this plugin doesn't support it yet.
It won't take me long to add it, I'll see if I can do it tomorrow, not promising anything I'm on vacation ;)

You mentioned something about all platforms, I'm not sure what to do on Android.
As I understand it, there isn't an equivalent to `accessibilityIdentifier` on Android.

The function `view.accessibiltyAnnouncement` is for getting the screen reader to read an announcement to the user, like 'Reloading list' or 'Book downloaded', I don't think it can help you here.

**Comment by grvermeulen** [comment]
Hi, Thanks again for the quick reply and all your effort! Much appreciated! Of course would it be ideal to use the accessibilityIdentifier property for both platforms, but if a similar property can be set for android that would be great too! Please do enjoy your vacation as well and thanks again for you effort!

**Comment by m-abs** [comment]
This should be solved by the latest 3.0.0- alpha

_Sent from my OnePlus ONEPLUS A3003 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_
