### ISSUE TITLE
Android Talkback reads value of textfield with attribute "secure"

### ISSUE THREAD

**Issue by oslc15** [Notalib/nativescript-accessibility-ext#39]
### Which platform(s) does your issue occur on?
- Android
- 7.0+ versions 
- devices

### Please, provide the following version numbers that your issue occurs with:

- CLI: 6.1.2
- Cross-platform modules: 6.1.1
- Runtime(s): 6.1.2
- Plugin(s): "@nota/nativescript-accessibility-ext": "^6.1.0-alpha.5"

### Please, tell us how to recreate the issue in as much detail as possible. 
Create a textfield with attribute secure and accessible true, enter a value in the textfield and
blur the field somehow. Move the talkback focus over to the textfield again and it will read the secure password as if it was in clear text.

### Is there any code involved? 
       <TextField
            secure="true"
            :accessible="true"
            :accessibilityLabel="test label"
            :accessibilityValue="value label"
        />

**Comment by m-abs** [comment]
Hi @oslc15 

I'm having trouble reproducing the issue.

As far as I can see NativeScript sets the proper values on the native view, so the value shouldn't be read by TalkBack.

I assume this option haven't been enabled on the device: https://support.google.com/accessibility/android/answer/6006977?hl=en

What device did you experience it on? Vendor and model?

Some vendors like Samsung have their own version of TalkBack and we've had some "fun" issues with that before.

**Comment by oslc15** [comment]
Hi @m-abs!

We have experienced this on devices from OnePlus 5T, Google Pixel 2, Google Pixel 2XL and from Samsung Note 8.
The setting "Speak Password" is not enabled on any of the devices, it was my first guess aswell... :P

I will try to reproduce this in a sampleproject for you. :)

**Comment by oslc15** [comment]
@m-abs i am not able to reproduce this in another project. Must be something within our code. :)
