### ISSUE TITLE
Limit for minimal font size

### ISSUE THREAD

**Issue by serrg1994** [Notalib/nativescript-accessibility-ext#48]
If in Accessibility settings set the smallest font size application looks awkward. Is the any way to set limit for font sizes ?

**Comment by m-abs** [comment]
It's not something I've considered before, but you should be able to use the css-helpers to redefine the css-vars.

```scss
.ns-root,
.ns-modal {
  &. a11y-fontscale-xs {
     /** Redefine css-vars here **/
  }
}
```
See variables here: https://github.com/Notalib/nativescript-accessibility-ext/blob/d1bc072af5acd88144fd84c3856b631bffc4202d/src/scss/a11y-helpers.scss#L42-L75
