### ISSUE TITLE
Upgrade to Nativescript 7

### ISSUE THREAD

**Issue by limux82** [Notalib/nativescript-accessibility-ext#53]
Using version 6.4.3 of the plugin in my app II see a lot of error in compilation related to changes in namespace in @nativescript/core. 

Is it  planned to upgrade te plugin to Nativescript 7?

e.g.

ERROR in ../node_modules/@nota/nativescript-accessibility-ext/ui/css-classes-helper.js
Module not found: Error: Can't resolve '@nativescript/core/application/application' in '/node_modules/@nota/nativescript-accessibility-ext/ui'
 @ ../node_modules/@nota/nativescript-accessibility-ext/ui/css-classes-helper.js 3:12-65
 @ ../node_modules/@nota/nativescript-accessibility-ext/views.js
 @ ../node_modules/@nota/nativescript-accessibility-ext/index.js
 @ ../node_modules/@nota/nativescript-accessibility-ext/angular/index.js
 @ ./app/app.module.ts
 @ ./main.ts

ERROR in ../node_modules/@nota/nativescript-accessibility-ext/utils/global-events.js
Module not found: Error: Can't resolve '@nativescript/core/data/observable/observable' in '/node_modules/@nota/nativescript-accessibility-ext/utils'
 @ ../node_modules/@nota/nativescript-accessibility-ext/utils/global-events.js 4:19-75
 @ ../node_modules/@nota/nativescript-accessibility-ext/ui/css-classes-helper.js
 @ ../node_modules/@nota/nativescript-accessibility-ext/views.js
 @ ../node_modules/@nota/nativescript-accessibility-ext/index.js
 @ ../node_modules/@nota/nativescript-accessibility-ext/angular/index.js
 @ ./app/app.module.ts
 @ ./main.ts

ERROR in ../node_modules/@nota/nativescript-accessibility-ext/ui/action-bar/action-bar.js
Module not found: Error: Can't resolve '@nativescript/core/ui/action-bar/action-bar' in '/node_modules/@nota/nativescript-accessibility-ext/ui/action-bar'
 @ ../node_modules/@nota/nativescript-accessibility-ext/ui/action-bar/action-bar.js 6:9-63 7:19-73
 @ ../node_modules/@nota/nativescript-accessibility-ext/pages.js
 @ ../node_modules/@nota/nativescript-accessibility-ext/index.js
 @ ../node_modules/@nota/nativescript-accessibility-ext/angular/index.js
 @ ./app/app.module.ts
 @ ./main.ts

ERROR in ../node_modules/@nota/nativescript-accessibility-ext/utils/global-events.js
Module not found: Error: Can't resolve '@nativescript/core/ui/activity-indicator/activity-indicator' in '/node_modules/@nota/nativescript-accessibility-ext/utils'
 @ ../node_modules/@nota/nativescript-accessibility-ext/utils/global-events.js 7:27-97
 @ ../node_modules/@nota/nativescript-accessibility-ext/ui/css-classes-helper.js
 @ ../node_modules/@nota/nativescript-accessibility-ext/views.js
 @ ../node_modules/@nota/nativescript-accessibility-ext/index.js
 @ ../node_modules/@nota/nativescript-accessibility-ext/angular/index.js
 @ ./app/app.module.ts
 @ ./main.ts

**Comment by m-abs** [comment]
I'm working on it, but it'll take some time to make the upgrade.

**Comment by m-abs** [comment]
Hi @limux82 

I've just published an alpha for NativeScript 7: `@nota/nativescript-accessibility-ext@7.0.0-alpha.0` could you test it for me?

**Comment by oslc15** [comment]
> Hi @limux82
> 
> I've just published an alpha for NativeScript 7: `@nota/nativescript-accessibility-ext@7.0.0-alpha.0` could you test it for me?

Hi m-abs, i will also begin testing NativeScript 7 this week, i will report if i find any issues 👍

**Comment by limux82** [comment]
Thanks @m-abs I will start testing!

**Comment by limux82** [comment]
I see some tsc errors to compile after the upgrade. Do I have to add some typings files as reference?

e.g.

 error TS2339: Property 'accessibilityLiveRegion' does not exist on type 'Label'.
this.messageLabel.nativeElement.accessibilityLiveRegion = AccessibilityLiveRegion.Assertive;

error TS2339: Property 'accessibilityAnnouncement' does not exist on type 'Label'.

37                         this.messageLabel.nativeElement.accessibilityAnnouncement(warningMessage);


 error TS2339: Property 'iosPostAccessibilityNotification' does not exist on type 'GridLayout'.

155                         .iosPostAccessibilityNotification('announcement', translation));

error TS2339: Property 'accessibilityHidden' does not exist on type 'RadListView'.

631         this.listViewElement.nativeElement.accessibilityHidden = true;

**Comment by oslc15** [comment]
Im experiencing the same issues as @limux82 with the alpha.0 release

**Comment by m-abs** [comment]
hi @limux82 and @oslc15,

It is something I need to fix,but you should be able to workaround it by casting nativeElement to any.

I'm on vacation this week without a computer to work on, so the earliest I can publish a new version is next week.

**Comment by m-abs** [comment]
It was just a packaging problem.

npmjs seems to be down at the moment, but I'll try to publish `7.0.0-alpha.1` later today or tomorrow.

**Comment by limux82** [comment]
Hi @m-abs Now the library compile! I have tested with Android and it works!

I'm not able to test in iOS because I have other plugins that have problems with ns7

**Comment by m-abs** [comment]
Since I haven't heard more about this issue, I'm assuming it is fixed and I'll close it.
