### ISSUE TITLE
How to change the Focus sequence of UI elements 

### ISSUE THREAD

**Issue by vickyATD** [Notalib/nativescript-accessibility-ext#62]
### Which platform(s) does your issue occur on?
- iOS or Android : Both
- emulator or device : Both

### Please, provide the following version numbers that your issue occurs with:
-->tns info : 
✔ Getting NativeScript components versions information...
⚠ Update available for component nativescript. Your current version is 8.1.4 and the latest available version is 8.1.5.
⚠ Update available for component @nativescript/core. Your current version is 7.0.13 and the latest available version is 8.1.5.
✔ Component @nativescript/ios has 8.1.0 version and is up to date.
✔ Component tns-android has 6.5.3 version and is up to date.

### Please, tell us how to recreate the issue in as much detail as possible. 
--> I want to change the focus sequence of UI elements on app. 

The way we write code and the way it renders on app has different order ,because of which the focus sequence is wrong when turning on the accessibility.

is there any property (similar to tabindex in web) where i can decide the order of focus on the app. 

### Is there any code involved? 
No

**Comment by m-abs** [comment]
Hi,

> is there any property (similar to tabindex in web) where i can decide the order of focus on the app.

Unfortunately, no there isn't a property for that.

**Comment by vickyATD** [comment]
Hi @m-abs ,

Thanks for replying.
Is there any alternative solution, which we can use to shift the focus of accessibility based on our requirement?

**Comment by m-abs** [comment]
Hi @vickyATD,

Not that I know of. It requires some changes to native code that you can't apply without patching nativescript's code all over the place.

**Comment by vickyATD** [comment]
can you guide over this as how to patch nativescript code to achieve the accessibility sequence. Thanks!
