### ISSUE TITLE
Error importing using Angular

### ISSUE THREAD

**Issue by tigrenok00** [Notalib/nativescript-accessibility-ext#9]
Hi,
I am importing the module like you suggested, and this is the error I'm getting:

![image](https://user-images.githubusercontent.com/23075641/27826617-5d071dc8-60bc-11e7-8ce2-66a08693713b.png)
![image](https://user-images.githubusercontent.com/23075641/27826729-d6a09cfe-60bc-11e7-9332-356b30de5db7.png)
![image](https://user-images.githubusercontent.com/23075641/27826621-65364b7c-60bc-11e7-8422-23c1b9392a6a.png)

This is my package.json:

 "tns-android": {
      "version": "3.1.1"
    }
  }, "dependencies": {
    "angular/common": "~4.1.0",
    "angular/compiler": "~4.1.0",
    "angular/core": "~4.1.0",
    "angular/forms": "~4.1.0",
    "angular/http": "~4.1.0",
    "angular/platform-browser": "~4.1.0",
    "angular/platform-browser-dynamic": "~4.1.0",
    "angular/router": "~4.1.0",
    "nota/nativescript-accessibility-ext": "^2.5.6",
    "nativescript-angular": "^3.1.1",
    "nativescript-angular-snapshot": "3.0.0-5.5.372.32",
    "nativescript-barcodescanner": "^2.4.0",
    "nativescript-dom": "^1.0.8",
    "nativescript-floatingactionbutton": "^3.0.0",
    "nativescript-loading-indicator": "^2.3.2",
    "nativescript-ngx-fonticon": "^2.2.0",
    "nativescript-screen-orientation": "^2.0.0",
    "nativescript-telerik-ui": "^3.0.1",
    "nativescript-theme-core": "1.0.4",
    "reflect-metadata": "~0.1.8",
    "rxjs": "~5.3.0",
    "tns-core-modules": "^3.1.0"
  },

**Comment by tigrenok00** [comment]
I've managed to install the 3.0 alpha version, I think, however, the **accessibilityAdjustsFontSize="false"** attribute set on Label doesn't seem to work. I want the label to not be resized and keep it's original font, is this the way to do it?
Thank you!

**Comment by m-abs** [comment]
Good to know you got it installed, do you know why it failed before?

**accessibilityAdjustsFontSize** is iOS-only, from your screenshot it looks like you're on Android.
Setting it to **false** on iOS should result in the default behavior, which is not scaling the font.

Android scales the font-size by it self, I don't know if it is possible to disable that behavior.

Once #1 is merged you should be able to use CSS to achieve it by scaling the font-size down on android for those elements.

**Comment by tigrenok00** [comment]
I think it was because the version installed by defaut was 2 and I needed 3.
Okay, thanks, I will appreciate if you put an example fot using CSS for this when it's ready.

**Comment by m-abs** [comment]
I wrote a possible workaround on your stackoverflow post:
https://stackoverflow.com/questions/44903670/how-to-ignore-accessibility-fonts-resize-in-nativescript/44917464?noredirect=1#comment77092406_44917464
